# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeInit < Formula
  desc "CLI tool to initialize projects with AI-assisted development configuration"
  homepage "https://github.com/drossan/claude-init"
  version "1.0.9"
  license "MIT"

  on_macos do
    url "https://github.com/drossan/claude-init/releases/download/v1.0.9/claude-init-1.0.9-darwin-all.tar.gz", using: GitHubReleaseDownloadStrategy
    sha256 "25c981cbd9afcbc9b5737d1e2064c46b91331005b25063bd80d501fafa593001"

    def install
      bin.install "claude-init"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drossan/claude-init/releases/download/v1.0.9/claude-init-1.0.9-linux-amd64.tar.gz", using: GitHubReleaseDownloadStrategy
      sha256 "501a7211869f44e88c05eb7ec2a7295be6f1633192622ee1ff5b39870b096564"
      def install
        bin.install "claude-init"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drossan/claude-init/releases/download/v1.0.9/claude-init-1.0.9-linux-arm64.tar.gz", using: GitHubReleaseDownloadStrategy
      sha256 "0dd4bff93ccc46b891fe21aadc7ac461750c0e95acbe98adafd27a075e30421d"
      def install
        bin.install "claude-init"
      end
    end
  end

  test do
    system "#{HOMEBREW_PREFIX}/bin/claude-init --version"
    stdout =~ /claude-init version/
  end
end
