# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GriddoEnv < Formula
  desc "Exporta tu colección http-request a postman"
  homepage "https://github.com/drossan/http2postman"
  version "0.0.2"

  on_macos do
    url "https://github.com/drossan/http2postman/releases/download/v0.0.2/http2postman_0.0.2_darwin_all.tar.gz"
    sha256 "5c7e935a0ff2c39b4db9cd2843a22d17e0d67ad868f7722323eaac150d35da46"

    def install
      bin.install "http2postman"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/drossan/http2postman/releases/download/v0.0.2/http2postman_0.0.2_linux_amd64.tar.gz"
        sha256 "74e1e5ea81f915b9543e6118b69040b36d572c23bdb4c2de2dd78bb8ed6acbb7"

        def install
          bin.install "griddo-env"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/drossan/http2postman/releases/download/v0.0.2/http2postman_0.0.2_linux_armv6.tar.gz"
        sha256 "97894ffe2cc127b71a42defb09497cff6fd531c51ceafbddcaf4df49bbb0355a"

        def install
          bin.install "griddo-env"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/drossan/http2postman/releases/download/v0.0.2/http2postman_0.0.2_linux_arm64.tar.gz"
        sha256 "3f96d8e4be1efcb79240bb20b4457d1809df52af50cf28893d130767219c7a36"

        def install
          bin.install "griddo-env"
        end
      end
    end
  end
end
