# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Http2postman < Formula
  desc "Exporta tu colección http-request a postman"
  homepage "https://github.com/drossan/http2postman"
  version "0.0.3"

  on_macos do
    url "https://github.com/drossan/http2postman/releases/download/v0.0.3/http2postman_0.0.3_darwin_all.tar.gz"
    sha256 "b08a885f2f46e1b59676c6e4cc44af0713e18fcdf607000e4f32ce359459b02f"

    def install
      bin.install "http2postman"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/drossan/http2postman/releases/download/v0.0.3/http2postman_0.0.3_linux_amd64.tar.gz"
        sha256 "cb0974abc2c1535279ea158f407b9cf83d26b8d482fb9ab04aa0857ad0cc0e95"

        def install
          bin.install "griddo-env"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/drossan/http2postman/releases/download/v0.0.3/http2postman_0.0.3_linux_armv6.tar.gz"
        sha256 "7efc044a645041ec34f07774f365e7ad8f1d7f3fc3af476281ec81accaf5bc81"

        def install
          bin.install "griddo-env"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/drossan/http2postman/releases/download/v0.0.3/http2postman_0.0.3_linux_arm64.tar.gz"
        sha256 "8363b940878f0a8d0e1b98c7599aee08cfdcf9e2a62d6354bfe0b4e05ce73d42"

        def install
          bin.install "griddo-env"
        end
      end
    end
  end
end
