# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Http2postman < Formula
  desc "Exporta tu colección http-request a postman"
  homepage "https://github.com/drossan/http2postman"
  version "1.1.0"

  on_macos do
    url "https://github.com/drossan/http2postman/releases/download/v1.1.0/http2postman_1.1.0_darwin_all.tar.gz"
    sha256 "d6155e56abef53db686d32560ce781974c5d6f1a7005983541b420f3841a6744"

    def install
      bin.install "http2postman"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/drossan/http2postman/releases/download/v1.1.0/http2postman_1.1.0_linux_amd64.tar.gz"
        sha256 "aeae9bfaf66256191d9eaed4bc4981d2a1801a57b04646571add057d22445e5d"

        def install
          bin.install "http2postman"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/drossan/http2postman/releases/download/v1.1.0/http2postman_1.1.0_linux_armv6.tar.gz"
        sha256 "798be44cbcd93dd01f991791794009ae89076f77cdd1b20ddc37b105a6a768a3"

        def install
          bin.install "http2postman"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/drossan/http2postman/releases/download/v1.1.0/http2postman_1.1.0_linux_arm64.tar.gz"
        sha256 "48138f7948a73fcacf40910e12a7979f05f29b50b647abbdffb6fa77ccc6955d"

        def install
          bin.install "http2postman"
        end
      end
    end
  end
end
