# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ListDir < Formula
  desc "Listar recursivamente archivos y directorios"
  homepage "https://github.com/drossan/list-dir-go"
  version "0.0.4"
  depends_on :macos

  url "https://github.com/drossan/list-dir-go/releases/download/v0.0.4/list-dir-go_0.0.4_darwin_all.tar.gz"
  sha256 "d9cae912f336893fda7363465322538b2df9cc148599d1ab84120650e3bd674a"

  def install
    bin.install "list-dir"
  end
end
